# Generated by Django 4.0.2 on 2022-04-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='avg_pp',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Average per person'),
        ),
    ]
