# Generated by Django 4.0.2 on 2022-04-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0002_ingredient_avg_pp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recepy',
            new_name='recipe',
        ),
    ]
