# Generated by Django 4.0.2 on 2022-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0005_alter_ingredient_avg_pp_alter_recipe_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='avg_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Average price per default unit'),
        ),
    ]
