# Generated by Django 4.0.2 on 2022-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0006_ingredient_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='default_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Default size of unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='avg_pp',
            field=models.FloatField(blank=True, null=True, verbose_name='Average per person in default units'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='avg_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Average price per default unit/size'),
        ),
    ]
