# Generated by Django 4.0.2 on 2022-05-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0008_event_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='beer_pairing',
            field=models.TextField(blank=True, null=True, verbose_name='Beer pairing'),
        ),
    ]
