# Generated by Django 4.0.2 on 2022-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0010_category_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='caboose.Category'),
        ),
    ]
