# Generated by Django 4.0.2 on 2022-05-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0012_facility_ship_event_ship_recipe_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_when_sailing', models.BooleanField(default=True, verbose_name='Works when sailing')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.facility')),
            ],
        ),
        migrations.AddField(
            model_name='ship',
            name='facility',
            field=models.ManyToManyField(blank=True, through='caboose.ShipFacility', to='caboose.Facility'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ManyToManyField(blank=True, to='caboose.Category'),
        ),
        migrations.AddField(
            model_name='shipfacility',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.ship'),
        ),
    ]
