# Generated by Django 4.0.2 on 2022-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0016_event_grouptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='grouptype',
            field=models.FloatField(choices=[(0.9, '<15'), (1, 'Mixed'), (1.1, '15-25'), (0.8, '60+')], default=1, verbose_name='Group composition (avg)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='facility',
            field=models.ManyToManyField(blank=True, null=True, to='caboose.Facility'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='caboose.Tag'),
        ),
    ]
