# Generated by Django 4.0.2 on 2023-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0018_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='event',
            name='plan',
            field=models.TextField(blank=True, null=True, verbose_name='Plan'),
        ),
    ]
