# Generated by Django 4.0.2 on 2023-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0019_alter_facility_options_event_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
