# Generated by Django 4.0.2 on 2023-07-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0022_alter_event_options_alter_event_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecipe',
            name='day',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrecipe',
            name='meal',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Diner'), (3, 'Other')], default=3, null=True),
        ),
    ]
