# Generated by Django 4.0.2 on 2023-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0024_alter_eventrecipe_options_recipe_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='synoniem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Synonyms'),
        ),
    ]
