# Generated by Django 4.0.2 on 2023-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0026_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='grouptype',
            field=models.FloatField(choices=[(0.9, '<15'), (1.0, 'Mixed'), (1.2, '15-25'), (0.8, '60+')], default=1.0, verbose_name='Group composition (avg)'),
        ),
    ]
