# Generated by Django 4.0.2 on 2023-08-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0028_recipesubs_alter_recipe_subs_recipesubs_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternative', to='caboose.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='alt',
            field=models.ManyToManyField(related_name='alt', through='caboose.AltIngredient', to='caboose.Ingredient'),
        ),
        migrations.DeleteModel(
            name='RecipeSubs',
        ),
        migrations.AddField(
            model_name='altingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.recipe'),
        ),
        migrations.AddField(
            model_name='altingredient',
            name='substitutes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='caboose.ingredient'),
        ),
        migrations.AddField(
            model_name='altingredient',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.tag'),
        ),
    ]
