# Generated by Django 4.0.2 on 2023-08-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0029_altingredient_recipe_alt_delete_recipesubs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altingredient',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caboose.tag'),
        ),
    ]
