# Generated by Django 4.0.2 on 2023-08-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0030_alter_altingredient_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='extra',
            field=models.ManyToManyField(through='caboose.EventIngredient', to='caboose.Ingredient'),
        ),
        migrations.AddField(
            model_name='eventingredient',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.event'),
        ),
        migrations.AddField(
            model_name='eventingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.ingredient'),
        ),
        migrations.AddField(
            model_name='eventingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.unit'),
        ),
    ]
