# Generated by Django 4.0.2 on 2023-11-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0032_allergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergen',
            field=models.ManyToManyField(blank=True, to='caboose.Allergen'),
        ),
    ]
