# Generated by Django 4.0.2 on 2023-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0033_ingredient_allergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price_json',
            field=models.TextField(editable=False, null=True),
        ),
    ]
