# Generated by Django 4.0.2 on 2024-06-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0034_recipe_price_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('primary', 'Blauw'), ('secondary', 'Grijs'), ('success', 'Groen'), ('warning', 'Geel'), ('info', 'Cyaan'), ('light', 'Zwart'), ('dark', 'Wit')], default='info', max_length=20, verbose_name='Tag color'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
