# Generated by Django 4.0.2 on 2024-06-11 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0036_remove_service_event_event_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventservice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.event'),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caboose.service'),
        ),
    ]
