# Generated by Django 4.0.2 on 2024-06-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0038_alter_event_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('priority', models.SmallIntegerField(choices=[(1, 'High'), (3, 'Medium'), (5, 'Low')], default=3)),
                ('status', models.SmallIntegerField(choices=[(0, 'Open'), (1, 'Done'), (2, 'Cancelled'), (3, 'Forfeited')], default=0, editable=False)),
            ],
        ),
    ]
