# Generated by Django 5.1.3 on 2025-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caboose', '0039_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source'),
        ),
    ]
